[package]
name = "pngme"
description = "A simple programm to hide messages in PNG files."
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "^2.0.12"
crc = "^3.3.0"

[dev-dependencies]
pretty_assertions = "^1.4.1"
